import React from 'react';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { ThemeRegistry } from '@/providers';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: {
	children: React.ReactNode;
}): React.ReactNode => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeRegistry>{children}</ThemeRegistry>
			</body>
		</html>
	);
};

export default RootLayout;
